# Generated by Django 5.0 on 2023-12-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='telephone',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
